### PR TITLE
fix: lag compensation crash with env_entity_maker

### PR DESCRIPTION
**Pull request by Kxnrl**
code ported from ModSharp, tested on win/linux.
cs2fixes need tests.

### CODE REVIEW

**Comment by xen-000** [comment]
Is there a reason for the cvar? And if so, you should add it to the cfg.

**Comment by Kxnrl** [comment]
> if so, you should add it to the cfg.

added

**Comment by PerfectLaugh** [comment]
I think the function type in Linux should be different than Windows one.
Linux的函数类型估计和Windows不同我感觉

Linux:
image
Windows:
image

**Comment by Kxnrl** [comment]
> I think the function type in Linux should be different than the Windows one. Linux的函数类型估计和Windows不同我感觉
> 
> Linux: image Windows: image

可是我已经跑了1个多月了. linux和win的服务器都有. 其实最开始我windows甚至也是5个参数, 也不会出现问题. 也不影响原本的功能.
a2 是 CBaseEntity, a3 是 bool, 这个2个平台都是一样的.

**Review by Vauff — APPROVED** [review]

**Pull request merged**
