### PR TITLE
Add method for PrecacheResource

### PR DESCRIPTION
**Pull request by Kroytz**
Credits: https://github.com/KillStr3aK/ResourcePrecacher/blob/master/Models/PrecacheContext.cs

### CODE REVIEW

**Comment by Poggicek** [comment]
We will first attempt to investigate other methods of getting precache context. Hooking a precache function of an entity that might not even spawn at all is definitely not ideal.

**Comment by Kxnrl** [comment]
> We will first attempt to investigate other methods of getting precache context. Hooking a precache function of an entity that might not even spawn at all is definitely not ideal.

could NOT precache sound resource on prop entity

**Comment by Poggicek** [comment]
Yeah, that wasn't even an idea. Entity spawning should just not be part of this equation. Game systems have a function that get called with a manifest as a param. That should be all you need, create a game system and make that function precache your own stuff

**Comment by xen-000** [comment]
Closing this in favor of #144.

**Pull request closed without merging**
